# Specify location of manifest files for each package manager

version: 2
updates:
  - package-ecosystem: "pip"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
