on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  ossie_job:
    runs-on: ubuntu-latest
    name: Audit Python dependencies 
    steps:
      - name: Test bash alias
        shell: bash
        run: |
          rc=/tmp/rcfile
          echo 'shopt -s expand_aliases' > $rc
          echo 'alias lll="ls -l" ' >> $rc

      - shell: bash
        run: |
          source /tmp/rcfile
          lll
          
      - uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
        with:
          egress-policy: audit
          disable-telemetry: true
