on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  ossie_job:
    runs-on: ubuntu-latest
    name: Audit Python dependencies 
    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run Packj.dev audit
        uses: ossillate-inc/packj.dev@v0.0.1-beta
        with:
            OSSIEBOT_ID: ${{ secrets.OSSIEBOT_ID }}
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
