on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  Tracee-Scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start Tracee profiling in background
      uses: aquasecurity/tracee-action@v0.1.0-start

    - name: Your CI Pipeline Step
      run: pip install dateutils

    - name: Stop and Check Tracee results and create a PR
      uses: aquasecurity/tracee-action@v0.1.0-stop
      with:
        fail-on-diff: "false"
        create-pr: "true"
